### ISSUE TITLE
Поддержка анализа текущего файла

### ISSUE THREAD

**Issue by clicman** [silverbulleters/sonarqube-inject-vsc#11]
На текущий момент линтер сканирует весь проект сразу и выводит все проблемы текущего воркспейса. Как насчет того, чтобы анализировать только открываемый файл?
А при каждом новом открываемом файле линтить его и добавлять в список проблем. Если же файл закрывается, то и скрывать проблемы этого файла.
Тогда все будет работать гипер-быстро ну а при необходимости всегда останется опция просканировать весь проект.

**Comment by nixel2007** [comment]
Поддерживаю, давно об этом думал

**Comment by nixel2007** [comment]
Реализовано в 1.2.0!
