### ISSUE TITLE
command 'sonarqube-inject.analyzeProject' not found

### ISSUE THREAD

**Issue by Alban34** [silverbulleters/sonarqube-inject-vsc#12]
When executing "SonarQube Inject" in VS Code, I only get the error: "command 'sonarqube-inject.analyzeProject' not found" with no clue how to solve it

**Comment by nixel2007** [comment]
Hello, @Alban34!

Which operating system do you use? Plugin version? VSC version?

Do you have any entries in developer tools' console? (You can open it through f1)

**Comment by Alban34** [comment]
Hi @nixel2007 

I'm using MacOS 10.12.3
Plugin version: 1.1.4 (I saw an update available, I'll give it a try)
VSC: 1.10.2

Nothing interesting in the console, just the same error message with the stacktrace:
workbench.main.js:103 command 'sonarqube-inject.analyzeProject' not founde.doShow @ workbench.main.js:103e.show @ workbench.main.js:103e.resume @ workbench.main.js:103(anonymous function) @ workbench.main.js:139e.invoke @ workbench.main.js:30e.fire @ workbench.main.js:30(anonymous function) @ workbench.main.js:108

**Comment by nixel2007** [comment]
> I'm using MacOS 10.12.3

I've fixed installing of sonarlint-cli on *nix and mac systems in 1.1.5
Please, try it. Feel free to post any questions!

**Comment by nixel2007** [comment]
Any news?

**Comment by Alban34** [comment]
1.1.5 seems to fix this issue but now I am an error each time I open a file with VS Code, so I removed the plugin.

**Comment by nixel2007** [comment]
What type of error do you have?
