### ISSUE TITLE
How to connect remote sonarqube settings

### ISSUE THREAD

**Issue by mgnfcnt** [silverbulleters/sonarqube-inject-vsc#15]
At sonarlint there is server option and we can add remote server with username and password. But here I could not understand how to perform this : 

SonarQube Inject: Create global config with credentials to servers

How to do that? Do this perform above action?

**Comment by nixel2007** [comment]
Hello!
You can execute this command through VSCode - press f1 and type "create global...". You'll see a command, press it.
This command creates a global.json at your appdata, also you can open it (via "open" button write to information message)

You need to do the same things with sonarlint.json config.

**Comment by mgnfcnt** [comment]
Thank you @nixel2007 Also Ctrl + Shift + P performs same actions.
