### ISSUE TITLE
Spawn ENOENT Error

### ISSUE THREAD

**Issue by equiman** [silverbulleters/sonarqube-inject-vsc#17]
Error: spawn C:\Users\myuser\.vscode\extensions\silverbulleters.sonarqube-inject-1.2.0\tools\sonarlint-cli\bin\sonarlint ENOENT

This message is showing constantly on my vscode.

**Comment by nixel2007** [comment]
Could you check this path - C:\Users\myuser.vscode\extensions\silverbulleters.sonarqube-inject-1.2.0\tool

does it contains any files?

**Comment by equiman** [comment]
.gitkeep and sonarlint-cli.zip files

**Comment by nixel2007** [comment]
Could you remove sonarlint-cli.zip and try to reopen editor?
You should see 2 notification messages at the top of the screen. Installation was started and Installation was successful.

If it won't help, try to extract content of zip-file to tools dir. You should get tools\sonarlint-cli\bin ... etc...

**Comment by equiman** [comment]
Extract with default windows unzip tool say: 
Windows Can't open the folder. The compressed (zipped) folder 'path..blahblachblah/sonarlint-cli'.zip' is invalid.

I'm try with 7-Zip and open it, but when i'm trying extract it say: 
Data error: sonarlint-cli\lib \sonarlinr-cli-2.1-SNAPSHOT.jar

I think this file is corrupt and maybe is the cause of this this bug.

**Comment by nixel2007** [comment]
Please, re-download file from https://github.com/nixel2007/sonarlint-cli/releases/tag/console-report-1.1

Put the both zip and its' content to `tools` dir

**Comment by equiman** [comment]
Now all is fine! 

Thanks!

**Comment by nixel2007** [comment]
:+1:
