### ISSUE TITLE
Error: spawn C:\Users\[username]\.vscode\extensions\silverbulleters.sonarqube-inject-1.2.1\tools\sonarlint-cli\bin\sonarlint ENOENT

### ISSUE THREAD

**Issue by tendersoft-mjb** [silverbulleters/sonarqube-inject-vsc#18]
When working with various files in VSCode I get the following message at the top:
**Error: spawn C:\Users\\[username]\\.vscode\extensions\silverbulleters.sonarqube-inject-1.2.1\tools\sonarlint-cli\bin\sonarlint ENOENT**

Appears constantly on keypress - extremely annoying.

**Comment by nixel2007** [comment]
Hello! Thanks for the report! 

Could you check existence of `C:\Users\KubuS\.vscode\extensions\silverbulleters\sonarqube-inject-1.2.1\tools\sonarlint-cli\bin\sonarlint` folder and binaries in it? 
Also do you have a sonarlint-cli.zip at `tools` folder?

**Comment by tendersoft-mjb** [comment]
There is only C:\Users\[username]\.vscode\extensions\silverbulleters.sonarqube-inject-1.2.1\tools with sonarlint-cli.zip in it, which has 0 bytes.

**Comment by nixel2007** [comment]
Looks like your sonarlint download is corrupted. 
Please, re-download it from https://github.com/nixel2007/sonarlint-cli/releases/tag/console-report-1.2 and extract to tools dir

**Comment by tendersoft-mjb** [comment]
I've just deleted the file and restarted VSCode. It then correctly proceeded with downloading and installing the tools. Now it works.

I you may want to detect this "0 byte" scenario and automate the re-installation process or at least provide some more meaningful error message.

**Comment by nixel2007** [comment]
I want to implement #14. It should solve the cause of this problem :) 

Issue is in Russian, but the main idea is to package this utility with extension itself
