### ISSUE TITLE
SonarQube extension installation does not use HTTP proxy settings

### ISSUE THREAD

**Issue by jpeffer** [silverbulleters/sonarqube-inject-vsc#2]
During the installation process of SonarQube support for Visual Studio Code, it appears that the HTTP(S) proxy settings, located in the user settings settings.json file, are ignored. Due to this issue, installation of the SonarLint CLI hangs.

**Comment by nixel2007** [comment]
Hi, @jpeffer!

Could you provide you settings.json (the proxy-part)?
I'll add the support of it.

Workaround:
* download [this zip](https://github.com/nixel2007/sonarlint-cli/releases/tag/console-report-1.0) and place it in `%USERPROFILE%\.vscode\extensions\silverbulleters.sonarqube-inject-1.1.1\tools` with `sonarlint-cli.zip` name
* extract this archive to `%USERPROFILE%\.vscode\extensions\silverbulleters.sonarqube-inject-1.1.1\tools\sonarlint-cli`

You need to get the following structure:
```
silverbulleters.sonarqube-inject-1.1.1
└───tools
              │   .gitkeep
              │   sonarlint-cli.zip
              │
              └───sonarlint-cli
                         ├───bin
                         │              sonarlint
                         │              sonarlint.bat
                         │
                         ├───lib
                         │              sonarlint-cli-2.1-SNAPSHOT.jar
                         │              sonarlint-client-api-2.4.jar
                         │
                         └───plugins
                                          sonar-java-plugin-4.0.jar
                                          sonar-javascript-plugin-2.14.jar
                                         sonar-php-plugin-2.8.jar

```

**Comment by jpeffer** [comment]
Here are example settings I found from [this](http://blog.majcica.com/2016/04/07/visual-studio-code-behind-a-proxy/) blog. I was connected through a corporate VPN, so I simply disconnected and completed the installation, but the workaround may be useful for others. Thanks!

`{
 "http.proxy": "http://my.proxy.address:8080",
 "https.proxy": "http://my.proxy.address:8080",
 "http.proxyStrictSSL": false
}`

**Comment by nixel2007** [comment]
I'll add it to our roadmap. 
P.S. You are the first non-local user of this extension. Does it suit your needs? Do you have any problems with setup (console encoding, glob patterns or whatever)? Any feedback is appreciated!

**Comment by jpeffer** [comment]
With my limited use so far, It's working perfectly! Only have used it for Java / JS applications, but no issues to report other than the proxy hiccup. Great stuff. I have contacted SonarSource, suggesting they include a reference to your extension from the SonarLint page.

**Comment by nixel2007** [comment]
@jpeffer I spoke with sonarsource some time ago. 
https://groups.google.com/forum/m/#!searchin/sonarlint/Vsc/sonarlint/SAelrKay438

The main idea - if we want a sonarsource support, we need to change the way this extension works. 
Now it runs through modified version of sonarlint cli and parses the stdout. SonarSource want a new non-comand line daemon and some kind of request-respond method via sockets or smth. 

So I decided to release this plugin in cli-mode and refactor it, when the new daemon will be released. 

Thanks for the respond! 

P. S. You can update the included support for Java and JS, if you run analysis in non-connected mode. Just download new versions of jars from sonarsource and put them in the plugins folder at tools/sonarlint-cli/plugins folder.

**Comment by nixel2007** [comment]
@jpeffer may i ask you to try new develop version?

Delete the installed plugin, unpack file, open VSC, open the extension tab, click on small menu in the top-right corner of the extension tab and select `install from VSIX`. Than reopen the editor.

[sonarqube-inject-1.1.1.zip](https://github.com/silverbulleters/sonarqube-inject-vsc/files/561569/sonarqube-inject-1.1.1.zip)

**Comment by jpeffer** [comment]
No luck, still hangs while attempting to install SonarLint. Is there a log I can capture that might help?

**Comment by nixel2007** [comment]
@jpeffer hm...
open dev tools, console tab. there must be an error message from plugin.
![devtools](https://cloud.githubusercontent.com/assets/1132840/19919859/6b6f7996-a0e6-11e6-9f0a-0704c101ca21.gif)

**Comment by jpeffer** [comment]
Here is the error I am receiving. Do you have a URL I could test with wget just to ensure our corporate firewall is not blocking the request? I would not expect it to result in a timeout, but it might be worth at least confirming I can reach the target.

![sonarqube-inject-1 1 1 vs code console output](https://cloud.githubusercontent.com/assets/1865672/19931766/17da9c9a-a0e4-11e6-8e20-168ecba5243a.png)

**Comment by nixel2007** [comment]
@jpeffer here is URL - `https://github.com/nixel2007/sonarlint-cli/releases/download/console-report-1.0/sonarlint-cli.zip`

Note: github use some redirects to final destination

/cc @kardanovir

**Comment by nixel2007** [comment]
maybe i should try to repack it as node module... if vsc marketplace have no limit on node_modules folder (it does on extension folder itself :( )

**Comment by jpeffer** [comment]
Yea pulling from github is no issue. It appears the proxy settings just are not being honored? Happy to try any other suggestions.

**Comment by jpeffer** [comment]
Looks like the Java plugin struggled with similar issues: 

https://github.com/redhat-developer/vscode-java/commit/6599e69e9636e3898eef23f1b726d950cdf6e846

https://github.com/redhat-developer/vscode-java/issues/42

**Comment by nixel2007** [comment]
[sonarqube-inject-1.1.1.zip](https://github.com/silverbulleters/sonarqube-inject-vsc/files/566960/sonarqube-inject-1.1.1.zip)

Check this out. I've added the strictSSL -> rejectUnauthorized setting, as mentioned at vscode-java

**Comment by nixel2007** [comment]
[sonarqube-inject-1.1.1.zip](https://github.com/silverbulleters/sonarqube-inject-vsc/files/566973/sonarqube-inject-1.1.1.zip)

one more ninja-edit. change `https.proxy` -> `http.proxy`

**Comment by jpeffer** [comment]
No luck :/

**Comment by atwayne** [comment]
I am having the same issue.
I took a deep look into the extension and I see you guys put a `https_proxy` attribute into the parameter options which get passed to `http.get()`, this won't work... 

This solution works:
http://stackoverflow.com/a/6781592/553073

However, almost everyone live with a proxy has to deal with the SSL certificates issue. 
See more details here:
http://stackoverflow.com/questions/13913941/how-to-fix-ssl-certificate-error-when-running-npm-on-windows

the build-in `http` library doesn't support this feature in an elegant way.
I am thinking to create a pull request to switch to the `request` library (https://github.com/request/request), which solves this issue perfectly.
The only concern I got is that this library is a 3rd library which means more dependency. 

Are you guys OK with this?

Thanks for the great pulgin, it is working perfectly with the workaround provided as above.

**Comment by nixel2007** [comment]
@atwayne hi! I am very glad to hear someone solved this issue! 
Sure, one more dep is not a problem and I appreciate any help :)

**Comment by nixel2007** [comment]
:ship: in 1.1.4

**Comment by jpeffer** [comment]
Validated that this is now working on our end. Thanks!

**Comment by nixel2007** [comment]
:+1:
