### ISSUE TITLE
command 'sonarqube-inject.createGlobalJson' not found

### ISSUE THREAD

**Issue by sdRichardWhitehouse** [silverbulleters/sonarqube-inject-vsc#22]
In VS Code, I've installed SonarLint and SonarQube as extensions, but everytime I try and run Ctrl-Shift-P createGlobalJson I get "command 'sonarqube-inject.createGlobalJson' not found".

I'm at a loss as to what I need to do to get this working.

Debugging addSubscriptions seems to fire in extension.js
e.g. (function addSubscriptions(context) {
	vscode.window.showInformationMessage("Adding Subscriptions"); 
)

**Comment by nixel2007** [comment]
hello!

A few questions:
which OS do you use?
could you check `C:\Users\your_profile\.vscode\extensions\silverbulleters.sonarqube-inject-1.2.1\tools` (for windows) for existance of sonarlint-cli.zip and sonarlint-cli folder?

**Comment by sdRichardWhitehouse** [comment]
Hi,

Thanks for your reply. Yes it's Windows, and sonarlint-cli and sonarlint-cli.zip exist in that location.

**Comment by nixel2007** [comment]
Sorry for the delay.
It's strange. If you have sonarlint-cli.zip in your folder, than all subsctiptions should be activated at startup.
Do other plugins start correctly? May be you have some heavy plugin with long warm-up time?
Did you try to reinstall this plugin?

**Comment by sdRichardWhitehouse** [comment]
The only extensions installed in VS Code are:
SonarLint 1.1.0 and SonarQube support for Visual Studio Code 1.2.1
It looks like the plugin is starting correctly due to the Adding Subscriptions message showing mentioned above. I have tried reinstalling the plugin and still the same thing.

**Comment by nixel2007** [comment]
Looks like we have some conflict with SonarLint extention. Could you try to deactivate it and reload an editor?

**Comment by sdRichardWhitehouse** [comment]
Unfortunately same issue. "SonarQube support for Visual Studio Code" is now the only extension installed.

**Comment by nixel2007** [comment]
Okey, so the last call... Which version of VSCode do you have?

**Comment by sdRichardWhitehouse** [comment]
1.13.1

**Comment by sdRichardWhitehouse** [comment]
So after quite a bit of debugging and stepping through, it dies on the following line in lintProvider.js:

sourcePath = path.relative(vscode.workspace.rootPath, textDocument.uri.fsPath);

This is because I had not opened a folder in VS Code, but instead just editing single files. lintProvider.js just falls over completely at this point and none of the following lines are run.
