### ISSUE TITLE
The plugin doesn't connect to SonarQube server with project inner organization.

### ISSUE THREAD

**Issue by artbear** [silverbulleters/sonarqube-inject-vsc#29]
The plugin doesn't connect to SonarQube server with project inner organization.
Error message is 
"INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 418960:23:26.124s
INFO: Final Memory: 9M/243M
INFO: ------------------------------------------------------------------------ERROR: Error executing SonarLint
ERROR: Error 404 on http://sonar.instance/api/qualityprofiles/search.protobuf?projectKey=my-project: Component key 'my-project' not found

ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarLint with the -e switch.
ERROR: Re-run SonarLint using the -X switch to enable full debug logging.
"

**Comment by artbear** [comment]
@nixel2007 @allustin ERROR: Error 404 on http://sonar.sec.vanessa.services/api/qualityprofiles/search.protobuf?projectKey=silverbulleters-gitoones: Component key 'silverbulleters-gitoones' not found

**Comment by nixel2007** [comment]
Fixed in 2.1
