### ISSUE TITLE
Multiple Sonarqube projects on a multiroot workspace

### ISSUE THREAD

**Issue by bgoorden** [silverbulleters/sonarqube-inject-vsc#30]
I have a multiroot project in visual studio code workspace. The two folders in this project use 2 different sonarqube projects. I configured them both with a sonarlint configuration file in the folder of the project. However only the configuration in the first folder is picked up and working. The other one is ignored. 

Will this configuration be supported in the future?

**Comment by nixel2007** [comment]
Yes, this is in the release plan. Thanks for the issue.
