### ISSUE TITLE
VSC runs analysis but it does not send results to server

### ISSUE THREAD

**Issue by Qocotzxin** [silverbulleters/sonarqube-inject-vsc#36]
Hi! I'm not getting any errors when I analyze a file (it finds code smells perfectly OK) but I am not getting the results in the server. I created both config files and the token is right (at first I got an error message related to the token but after fixing it and running the binding again it got solved). One more thing, if I run the test from the Windows console I receive the results in the server just fine, I'm having trouble only with the extension from VSC.

Any thoughts about this issue? It's getting a little difficult to determine the cause since it doesn't show any errors. 

I'm running it on Windows 10 and the extension as well as VSC are updated.

Thanks!

**Comment by nixel2007** [comment]
Hello.

Sonarlint-inject isn't supposed to publish result of analyze to your SQ server - it only displays issues in IDE.
If you need to push results to server, you need to run sonar-scanner ulility.

**Comment by Qocotzxin** [comment]
Excellent! Thanks for the answer @nixel2007 ! Then I will try to use Jenkins and automatize that part of the process. Have a nice week!

**Comment by nixel2007** [comment]
Jenkins is an excelent tool for this :)
see you.
