### ISSUE TITLE
Can't execute the "SonarQube Inject: Create global config with credentials to servers" command

### ISSUE THREAD

**Issue by abdel1314** [silverbulleters/sonarqube-inject-vsc#38]
I can't execute the "SonarQube Inject: Create global config with credentials to servers" command, I have the following message : 

> $ SonarQube Inject: Create global config with credentials to servers
bash: SonarQube: command not found

I'm using windows 7

**Comment by nixel2007** [comment]
Hello. Please, open any supported file and try again.

**Comment by abdel1314** [comment]
Hello, excuse my ignorance, but what do you mean by "supported file", I'm trying to execute this commande inside my project and it isn't work, can you give me an example of a "supported file" please.

**Comment by nixel2007** [comment]
And...
> bash: SonarQube: command not found

do you try to run this command in VSC terminal? You need to pick this command from command pallete (F1)

**Comment by abdel1314** [comment]
Actually I run this command in VSC terminal, I pick this command from command pallet and this works fine now.
Thank you @nixel2007
