### ISSUE TITLE
check depends

### ISSUE THREAD

**Issue by allustin** [silverbulleters/sonarqube-inject-vsc#5]
![image](https://cloud.githubusercontent.com/assets/55323/21468122/a8e54668-ca15-11e6-81a5-ef1a43984a2d.png)

![image](https://cloud.githubusercontent.com/assets/55323/21468124/be268b72-ca15-11e6-96af-830f379bae4f.png)

@nixel2007  - can we fix it ?

**Comment by nixel2007** [comment]
I think, we can bump all deps without any errors. But we still need to make new release.

**Comment by nixel2007** [comment]
Done in 1.1.2
